### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by mmcc** [citrus/spree_essential_cms#6]
I consider this a pretty minor bug in a very useful extension, but it appears that it is not adding new pages to the menu regardless of the "visible" setting. I can access the page fine by going to the url manually, it just isn't adding the link to the main menu. This is in 0.3.0rc1. Thank you for the great resource regardless!

**Comment by citrus** [comment]
Thanks for pointing this out! I'll try and take a look tonight.

**Comment by citrus** [comment]
This is fixed on master and I'll be releasing a new stable version soon.

**Comment by dp6ai** [comment]
I'm still having this issue with the latest version pushed on friday night.  Is there a fix?

thanks

p

**Comment by citrus** [comment]
I just added tests to verify this behavior and it seems to be working fine. Are you overwriting `@pages` anywhere?

**Comment by dp6ai** [comment]
I dont think i've done anything stupid.

Added two pages, faq and test. 

then my html is looking like this:

```
        <ul id="main-nav-bar" class="inline" data-hook="">
          <li id="home-link" data-hook="">
            <a href="/">Home</a>
          </li>
          <li id="link-to-cart" data-hook="">
        </ul>
```

I assume the new pages should be added here?

thanks

**Comment by citrus** [comment]
Did you add an override to include the main menu?

``` ruby
# app/overrides/main_menu.rb
Deface::Override.new(:virtual_path  => "spree/shared/_store_menu",
                     :name          => "spree_essential_cms_main_menu_items",
                     :insert_after  => "#home-link[data-hook]",
                     :partial       => "spree/shared/main_menu_items",
                     :disabled      => false)
```

**Comment by dp6ai** [comment]
Sorry to take so long to get back.

Adding the override has fixed the issue. 

thanks

**Comment by citrus** [comment]
Right on glad that you got it working!
